import type { WallPost } from "@/lib/campus-wall";

export const DEMO_POSTS: WallPost[] = [
  {
    id: "demo-news-1",
    category: "news",
    title: "秋季社团招新市集，本周四在风雨长廊见",
    content:
      "48 个学生社团会把摊位搬到风雨长廊。除了现场招新，还有街舞快闪、乐队暖场和公益社团的旧书交换。建议错峰前往，别忘了带校园卡。",
    tags: ["社团招新", "本周活动"],
    author_name: "观澜学生会",
    author_badge: "官方",
    is_anonymous: false,
    created_at: "2026-08-24T08:30:00+08:00",
    time_label: "今天 08:30",
    likes_count: 126,
    comment_count: 18,
    comments: [
      {
        id: "demo-comment-1",
        content: "摄影社今年会有暗房体验吗？",
        author_name: "南区同学",
        is_anonymous: false,
        created_at: "2026-08-24T09:08:00+08:00",
        time_label: "今天 09:08",
      },
      {
        id: "demo-comment-2",
        content: "有的，在 27 号摊位，欢迎来玩！",
        author_name: "摄影社",
        is_anonymous: false,
        created_at: "2026-08-24T09:16:00+08:00",
        time_label: "今天 09:16",
      },
    ],
    liked: false,
    is_pinned: true,
  },
  {
    id: "demo-news-2",
    category: "news",
    title: "图书馆期初延时开放安排",
    content:
      "从本周起，图书馆一至四层开放至 22:30，一楼自习区延长至 23:30。闭馆前十五分钟会进行广播提醒，请带好随身物品。",
    tags: ["图书馆", "开放时间"],
    author_name: "图书馆读者服务部",
    author_badge: "官方",
    is_anonymous: false,
    created_at: "2026-08-23T18:20:00+08:00",
    time_label: "昨天 18:20",
    likes_count: 89,
    comment_count: 7,
    comments: [],
    liked: false,
  },
  {
    id: "demo-daily-1",
    category: "daily",
    title: "操场的晚霞像被打翻的橘子汽水",
    content:
      "下课刚好赶上这一场。广播里在放老歌，跑道上有人慢慢散步，新学期突然就有了一点具象的期待。",
    tags: ["今日份晚霞", "校园摄影"],
    author_name: "一颗青柠",
    is_anonymous: false,
    created_at: "2026-08-24T18:42:00+08:00",
    time_label: "今天 18:42",
    likes_count: 214,
    comment_count: 24,
    comments: [
      {
        id: "demo-comment-3",
        content: "我也看到了！教学楼四楼的视角超好。",
        author_name: "小满",
        is_anonymous: false,
        created_at: "2026-08-24T18:48:00+08:00",
        time_label: "今天 18:48",
      },
    ],
    liked: true,
  },
  {
    id: "demo-daily-2",
    category: "daily",
    title: "二食堂一楼的桂花冰豆花回来了",
    content:
      "甜度比上学期低一点，桂花香很足，下午三点去不用排队。负责窗口的阿姨说这周每天限量，路过可以试试。",
    tags: ["食堂测评", "二食堂"],
    author_name: "吃遍观澜",
    is_anonymous: false,
    created_at: "2026-08-24T15:12:00+08:00",
    time_label: "今天 15:12",
    likes_count: 76,
    comment_count: 12,
    comments: [],
    liked: false,
  },
  {
    id: "demo-lost-1",
    category: "lost_found",
    title: "寻找一张蓝色卡套里的校园卡",
    content:
      "今天中午从三教走到二食堂的路上遗失，卡套背面贴着一枚银杏叶贴纸。如果有同学捡到，麻烦在评论里告诉我，非常感谢。",
    tags: ["校园卡", "三教"],
    author_name: "匿名同学",
    is_anonymous: true,
    created_at: "2026-08-24T13:26:00+08:00",
    time_label: "今天 13:26",
    likes_count: 18,
    comment_count: 5,
    comments: [
      {
        id: "demo-comment-4",
        content: "二食堂失物处有一张类似的，可以去窗口问问。",
        author_name: "路过的同学",
        is_anonymous: false,
        created_at: "2026-08-24T13:41:00+08:00",
        time_label: "今天 13:41",
      },
    ],
    liked: false,
    location: "三教 → 二食堂",
    resolution_status: "open",
    lost_found_type: "lost",
    item_category: "documents",
    occurred_at: "2026-08-24T12:20:00+08:00",
  },
  {
    id: "demo-lost-2",
    category: "lost_found",
    title: "在篮球场看台捡到一副蓝牙耳机",
    content:
      "白色充电盒，右侧有一道浅划痕。已经交到北门值班室，请失主说明耳机品牌和保护壳细节后领取。",
    tags: ["蓝牙耳机", "北门值班室"],
    author_name: "林间风",
    is_anonymous: false,
    created_at: "2026-08-23T20:04:00+08:00",
    time_label: "昨天 20:04",
    likes_count: 32,
    comment_count: 3,
    comments: [],
    liked: false,
    location: "北区篮球场",
    resolution_status: "resolved",
    lost_found_type: "found",
    item_category: "electronics",
    occurred_at: "2026-08-23T19:30:00+08:00",
  },
  {
    id: "demo-confession-1",
    category: "confession",
    title: "想谢谢昨晚帮忙搬画板的两位同学",
    content:
      "昨晚突然下雨，我一个人在艺术楼门口手忙脚乱。谢谢你们一路帮我把画板搬到宿舍楼下，还把唯一的伞留给了我。没来得及问名字，希望你们能看到。",
    tags: ["谢谢你", "雨夜善意"],
    author_name: "匿名同学",
    is_anonymous: true,
    created_at: "2026-08-24T11:06:00+08:00",
    time_label: "今天 11:06",
    likes_count: 168,
    comment_count: 19,
    comments: [
      {
        id: "demo-comment-5",
        content: "这种具体的小善意真的很打动人。",
        author_name: "匿名同学",
        is_anonymous: true,
        created_at: "2026-08-24T11:18:00+08:00",
        time_label: "今天 11:18",
      },
    ],
    liked: false,
  },
  {
    id: "demo-confession-2",
    category: "confession",
    title: "致每天清晨六点半在操场跑步的你",
    content:
      "不认识你，但每次路过都觉得很有力量。谢谢你的坚持也顺便鼓励了一个总想赖床的陌生人。祝你这个学期一切顺利。",
    tags: ["远远欣赏", "早起的人"],
    author_name: "匿名同学",
    is_anonymous: true,
    created_at: "2026-08-23T22:18:00+08:00",
    time_label: "昨天 22:18",
    likes_count: 96,
    comment_count: 8,
    comments: [],
    liked: false,
  },
  {
    id: "demo-tree-1",
    category: "tree_hole",
    content:
      "开学才两天，看到身边的人都目标明确，只有我还在原地打转。知道不该比较，但晚上安静下来还是会焦虑。想听听大家是怎么慢慢找到节奏的。",
    tags: ["新学期", "慢慢来"],
    author_name: "树洞 0427",
    is_anonymous: true,
    created_at: "2026-08-24T00:37:00+08:00",
    time_label: "今天 00:37",
    likes_count: 73,
    comment_count: 31,
    comments: [
      {
        id: "demo-comment-6",
        content: "先只安排好明天，不用一次想完整个学期。你已经在往前走了。",
        author_name: "树洞 1180",
        is_anonymous: true,
        created_at: "2026-08-24T00:45:00+08:00",
        time_label: "今天 00:45",
      },
      {
        id: "demo-comment-7",
        content: "允许自己有一段缓冲期，找到自己的速度就好。",
        author_name: "匿名同学",
        is_anonymous: true,
        created_at: "2026-08-24T01:02:00+08:00",
        time_label: "今天 01:02",
      },
    ],
    liked: true,
  },
  {
    id: "demo-tree-2",
    category: "tree_hole",
    content:
      "第一次离家这么远，白天忙起来还好，晚上回宿舍会突然很想家。今天和家里打电话时没敢说，怕他们担心。写在这里，好像就轻一点了。",
    tags: ["想家", "晚安"],
    author_name: "树洞 0731",
    is_anonymous: true,
    created_at: "2026-08-23T23:42:00+08:00",
    time_label: "昨天 23:42",
    likes_count: 112,
    comment_count: 26,
    comments: [],
    liked: false,
  },
];

